#!/usr/bin/env bash
# 노드가 클러스터 안 GitLab 레지스트리에서 pull 할 수 있게 만든다.
# 노드 상태라 ArgoCD 가 손댈 수 없어 스크립트로 둔다 — LOCAL-DEPLOYMENT §25-1 ·
# Gotcha 126 의 절차를 그대로 옮긴 것이다.
#
# 왜 필요한가
#   레지스트리는 평문 HTTP 인데 containerd 는 미러 설정이 없으면 HTTPS 로 붙는다
#   (`http: server gave HTTP response to HTTPS client`). 그리고 노드는 CoreDNS 를
#   쓰지 않으므로 FQDN 이 풀리지 않아 /etc/hosts 에 ClusterIP 가 필요하다
#   (Gotcha 52 ①). 2026-09-11 까지 이 파일이 없어 **거기서 pull 한 적이 한 번도
#   없었다** — 로컬 빌드 이미지가 돌던 것은 containerd 로 직접 반입하고
#   `imagePullPolicy: IfNotPresent` 이기 때문이다.
#
# ★★★ 2026-10-05 에 이 스크립트가 **control-plane 의 API 를 내렸다.** 생성하는
#   YAML 의 주석에 한글이 들어 있었고, 그 바이트가 이중 인코딩되어 C1 제어문자가
#   되자 k3s 가 `yaml: control characters are not allowed` 로 거부하고
#   `Waiting to retrieve agent configuration; server is not ready` 를 반복했다.
#   그래서 이 스크립트는 세 가지를 지킨다:
#     ① **생성하는 파일은 ASCII 만** 쓴다 — 기계가 엄격히 파싱하는 파일에 사람
#        말을 넣지 않는다(Gotcha 83·160 과 같은 뿌리: 데이터와 산문을 섞지 말 것).
#     ② 쓰기 전에 **비-ASCII 가 0인지 검사**하고, 아니면 쓰지 않는다.
#     ③ 재시작 뒤 **유닛이 active 가 되는지 확인**하고, 아니면 실패로 끝낸다.
#        — 전에는 재시작만 걸고 넘어가서 노드가 깨진 채 남았다.
#
# ★★ 그리고 **자기 노드를 마지막에** 처리한다. 이 노드에서 k3s 를 재시작하면
#   그 순간 셸과 kubectl 이 끊겨 루프의 나머지가 돌지 않는다 — 실측으로 103 만
#   적용되고 104 는 **오류 없이** 건너뛰어졌다.
#
# 쓰는 법
#   bash local/configure-node-registry.sh          # 모든 노드에 적용
#   bash local/configure-node-registry.sh --check  # 반영 여부만 (게이트용 exit 1)
#
# ★ control-plane 에서 돌릴 것 — 다른 노드로는 root ssh 로 간다(Gotcha 175).
set -Eeuo pipefail
export KUBECONFIG="${KUBECONFIG:-/etc/rancher/k3s/k3s.yaml}"

REGISTRY_SVC="${REGISTRY_SVC:-gitlab-registry}"
REGISTRY_NS="${REGISTRY_NS:-local}"
REGISTRY_PORT="${REGISTRY_PORT:-5050}"
FQDN="${REGISTRY_SVC}.${REGISTRY_NS}.svc.cluster.local"
SHORT="${REGISTRY_SVC}"
# ★ 표식도 ASCII 다 — /etc/hosts 역시 기계가 읽는다.
MARK="# oneinchmarket-registry (local/configure-node-registry.sh)"

CHECK=no
[ "${1:-}" = "--check" ] && CHECK=yes

log()  { echo "[registry] $*"; }
warn() { echo "[registry] WARN: $*" >&2; }
fail() { echo "[registry] FAIL: $*" >&2; exit 1; }

SELF_IP="$(hostname -I | awk '{print $1}')"
ALL_IPS="$(kubectl get nodes \
  -o jsonpath='{range .items[*]}{.status.addresses[?(@.type=="InternalIP")].address}{"\n"}{end}' \
  2>/dev/null | grep -v '^$' | tr '\n' ' ')"
[ -n "$ALL_IPS" ] || fail "노드 목록을 읽지 못했다 — control-plane 에서 돌릴 것"

CIP="$(kubectl -n "$REGISTRY_NS" get svc "$REGISTRY_SVC" \
        -o jsonpath='{.spec.clusterIP}' 2>/dev/null || true)"
if [ -z "$CIP" ]; then
  warn "svc ${REGISTRY_NS}/${REGISTRY_SVC} 가 없다 — /etc/hosts 는 건너뛴다(GitLab 은 wave 5)"
else
  # ★ 루프백을 넣으면 kubelet 의 pull 이 깨진다(Gotcha 52 ①). ClusterIP 는
  #   Service 를 다시 만들면 바뀌므로 매번 조회해 다시 쓴다.
  case "$CIP" in 127.*|localhost) fail "ClusterIP 가 루프백(${CIP})이다 — kubelet 의 pull 이 깨진다";; esac
  log "레지스트리 ClusterIP: $CIP"
fi

# ── 생성 내용: ASCII 만 ────────────────────────────────────────────
REG_CONTENT=$(cat <<YAML
# Generated by local/configure-node-registry.sh -- do not edit by hand.
# ASCII only: k3s parses this with a strict YAML reader and rejects C1 control
# characters. A non-ASCII comment here once took the API server down.
# Both the short name and the FQDN are listed: manifests use the FQDN, while
# older imports and ad-hoc commands may use the short name.
mirrors:
  "${FQDN}:${REGISTRY_PORT}":
    endpoint: ["http://${FQDN}:${REGISTRY_PORT}"]
  "${SHORT}:${REGISTRY_PORT}":
    endpoint: ["http://${SHORT}:${REGISTRY_PORT}"]
YAML
)
# ★ 가드 — 쓰기 전에 본다. "비어 있지 않다" 가 아니라 "ASCII 인가" 로 판정한다.
if LC_ALL=C printf '%s' "$REG_CONTENT" | LC_ALL=C grep -q '[^ -~'$'\t'']'; then
  fail "생성 내용에 비-ASCII 가 있다 — k3s 가 거부한다. 주석을 영문으로 둘 것"
fi

node_script() {
cat <<'NODE'
set -Eeuo pipefail
REG=/etc/rancher/k3s/registries.yaml
# 내용은 base64 env 로 받는다 — stdin 은 이 스크립트 자체가 쓴다.
# (둘 다 stdin 으로 넘기려다 한 번 충돌시켰다.)
NEW="$(printf %s "$REG_B64" | base64 -d)"
if LC_ALL=C printf '%s' "$NEW" | LC_ALL=C grep -q '[^ -~'"$(printf '\t')"']'; then
  echo "  거부: 받은 내용에 비-ASCII 가 있다" >&2; exit 1
fi
CHANGED=no
mkdir -p /etc/rancher/k3s
if [ ! -f "$REG" ] || [ "$(cat "$REG")" != "$NEW" ]; then
  printf '%s\n' "$NEW" > "$REG"; CHANGED=yes
fi
if [ -n "${CIP:-}" ]; then
  HOSTLINE="${CIP} ${FQDN} ${SHORT} ${MARK}"
  if ! grep -qxF "$HOSTLINE" /etc/hosts; then
    grep -vF "$MARK" /etc/hosts > /etc/hosts.new
    printf '%s\n' "$HOSTLINE" >> /etc/hosts.new
    cat /etc/hosts.new > /etc/hosts; rm -f /etc/hosts.new
    CHANGED=yes
  fi
fi
UNIT=k3s; systemctl is-enabled k3s >/dev/null 2>&1 || UNIT=k3s-agent
if [ "$CHANGED" != yes ]; then echo "  이미 같다 - 재시작하지 않는다"; exit 0; fi
systemctl restart "$UNIT"
# ★ 재시작을 걸고 넘어가지 않는다 — active 가 되는지 끝까지 본다.
for i in $(seq 1 20); do
  [ "$(systemctl is-active "$UNIT")" = active ] && break
  sleep 6
done
if [ "$(systemctl is-active "$UNIT")" != active ]; then
  echo "  ★ $UNIT 가 active 가 되지 않았다 — 최근 로그:" >&2
  journalctl -u "$UNIT" -n 4 --no-pager -o cat 2>/dev/null | sed 's/^/    /' >&2
  exit 1
fi
echo "  변경됨 - $UNIT 재시작 후 active"
NODE
}

check_script() {
cat <<'NODE'
set -Eeuo pipefail
REG=/etc/rancher/k3s/registries.yaml
UNIT=k3s; systemctl is-enabled k3s >/dev/null 2>&1 || UNIT=k3s-agent
[ -f "$REG" ] || { echo "  registries.yaml 없음"; exit 1; }
NONASCII=$(LC_ALL=C grep -c '[^ -~'"$(printf '\t')"']' "$REG" || true)
MIRRORS=$(grep -c 'endpoint:' "$REG" || true)
HOSTS=$(grep -c 'oneinchmarket-registry' /etc/hosts || true)
FT=$(stat -c %Y "$REG")
ST=$(date -d "$(systemctl show "$UNIT" -p ActiveEnterTimestamp --value)" +%s 2>/dev/null || echo 0)
ACT=$(systemctl is-active "$UNIT")
[ "$NONASCII" = 0 ] || { echo "  ★ 비-ASCII $NONASCII 줄 — k3s 가 거부한다"; exit 1; }
[ "$ACT" = active ] || { echo "  ★ $UNIT 가 $ACT 다"; exit 1; }
# ★ 핵심: containerd 는 기동 때만 읽는다. 파일이 더 나중이면 반영되지 않았다.
if [ "$ST" -gt 0 ] && [ "$FT" -gt "$ST" ]; then
  echo "  미러 ${MIRRORS} · hosts ${HOSTS}줄 · ★ 파일이 $UNIT 기동보다 나중 — 반영 안 됨"; exit 1
fi
echo "  미러 ${MIRRORS} · hosts ${HOSTS}줄 · $UNIT active · 기동 이후 변경 없음 — 반영됨"
NODE
}

REG_B64="$(printf '%s\n' "$REG_CONTENT" | base64 -w0)"
ENVS="REG_B64='${REG_B64}' CIP='${CIP}' FQDN='${FQDN}' SHORT='${SHORT}' MARK='${MARK}'"

# ★ 자기 노드를 마지막에 — 재시작이 루프를 끊는다.
ORDERED=""
for ip in $ALL_IPS; do [ "$ip" = "$SELF_IP" ] || ORDERED="$ORDERED $ip"; done
case " $ALL_IPS " in *" $SELF_IP "*) ORDERED="$ORDERED $SELF_IP";; esac
log "노드 처리 순서:$ORDERED (자기 노드 $SELF_IP 마지막)"

RC=0
for ip in $ORDERED; do
  echo "=== $ip ==="
  if [ "$CHECK" = yes ]; then
    if [ "$ip" = "$SELF_IP" ]; then check_script | bash || RC=1
    else check_script | ssh -o BatchMode=yes -o ConnectTimeout=10 "root@${ip}" bash || RC=1; fi
  else
    if [ "$ip" = "$SELF_IP" ]; then
      node_script | env REG_B64="$REG_B64" CIP="$CIP" FQDN="$FQDN" SHORT="$SHORT" MARK="$MARK" bash || RC=1
    else
      node_script | ssh -o BatchMode=yes -o ConnectTimeout=10 "root@${ip}" "${ENVS} bash -s" || RC=1
    fi
  fi
done

if [ "$CHECK" = yes ]; then
  [ "$RC" = 0 ] && log "전 노드 반영됨" || log "반영되지 않은 노드가 있다"
  exit "$RC"
fi
log "★ 판정은 파일이 아니라 실제로 pull 이 되는지다 — 옆문 사본이 남아 있으면"
log "  IfNotPresent 가 그것을 쓰므로 고쳤는지 알 수 없다(Gotcha 85):"
log "    k3s ctr -n k8s.io images rm <이미지>"
log "    kubectl -n local run pulltest --image=<이미지> --restart=Never --command -- true"
exit "$RC"
