#!/bin/bash
# 외부 접속의 **노드 쪽** 전제 — 와일드카드 DNS 와 WireGuard VPN.
#
#   bash local/external-access-node.sh --check        검사만 (0 통과 / 1 실패 / 2 측정 불가)
#   bash local/external-access-node.sh                적용하고 되읽어 확인
#   bash local/external-access-node.sh --peer <이름>   VPN 피어 하나를 발급
#
# ★★ 왜 노드 상태인가 — 이 둘은 쿠버네티스 오브젝트로 담을 수 없다.
#   `registries.yaml`(Gotcha 126)·`/etc/resolv.conf` 고정과 같은 부류이고,
#   그래서 **스크립트로 두고 되읽어 확인한다**(Gotcha 183). 노드 상태로
#   방치하면 재구축 때 빠뜨리고 증상이 원인과 아주 멀다.
#
# ★★★ 443·80 은 여기서 다루지 않는다. `kubernetes/overlays/local/
#   external-access/external-ips-service.yaml` 이 처리한다 — 노드 iptables
#   DNAT 를 쓰려 했다가 **측정해서 버렸다**: 규칙은 맞는데(실측 2패킷)
#   연결이 000 이다. Cilium 이 NodePort 를 tc ingress 의 eBPF 에서 처리하고
#   그것은 netfilter 보다 앞에서 끝나기 때문이다. 측정 기록은 그 파일에 있다.
#
# ★ 이 스크립트가 **재지 못하는 것**은 끝에서 스스로 밝힌다.
set -u

DOMAIN="oneinchmarket.local"
NODE_IP="192.168.0.103"
LAN_CIDR="192.168.0.0/24"
VPN_CIDR="172.30.0.0/24"
VPN_SERVER_IP="172.30.0.1"
VPN_PORT="51820"
WG_IF="oim0"
WG_DIR="/etc/wireguard"
WG_CONF="$WG_DIR/$WG_IF.conf"
WG_PEERS="$WG_DIR/peers"
DNSMASQ_BIN="/usr/sbin/dnsmasq"
DNSMASQ_CONF="/etc/oim-dnsmasq.conf"
DNS_UNIT_NAME="oim-wildcard-dns.service"
DNS_UNIT="/etc/systemd/system/oim-wildcard-dns.service"

PASS=0; FAIL=0; UNMEAS=0
ok()   { printf '  [OK]    %s\n' "$1"; PASS=$((PASS+1)); }
bad()  { printf '  [FAIL]  %s\n' "$1"; FAIL=$((FAIL+1)); }
skip() { printf '  [측정불가] %s\n' "$1"; UNMEAS=$((UNMEAS+1)); }
head2(){ printf '\n== %s ==\n' "$1"; }

# ★ 생성 파일은 ASCII 만 담는다. 비-ASCII 가 섞이면 엄격히 파싱하는 쪽이
#   거부하고 증상이 원인을 가리키지 않는다 — 한글 주석 한 줄이 control-plane
#   의 API 를 내린 적이 있다(Gotcha 177). 쓴 뒤 **세어서** 확인한다.
assert_ascii() {
  local f="$1" n
  n=$(LC_ALL=C grep -c '[^ -~	]' "$f" 2>/dev/null || true)
  [ -n "$n" ] || n=0
  if [ "$n" != "0" ]; then
    bad "$f 에 비-ASCII $n 줄"
    return 1
  fi
  return 0
}

# ★ 재시작을 걸고 넘어가지 않는다. active 가 되는지 끝까지 보고 아니면
#   journal 과 함께 실패로 끝낸다(Gotcha 177 — 전에는 넘어가서 노드가
#   깨진 채 남았고 다른 명령이 실패할 때까지 몰랐다).
restart_verify() {
  local unit="$1" i
  systemctl restart "$unit" >/dev/null 2>&1
  for i in 1 2 3 4 5 6 7 8 9 10; do
    [ "$(systemctl is-active "$unit" 2>/dev/null)" = "active" ] && { ok "$unit active"; return 0; }
    sleep 1
  done
  bad "$unit 이 active 가 되지 않았다"
  journalctl -u "$unit" -n 15 --no-pager 2>/dev/null | sed 's/^/      /'
  return 1
}

need_root() {
  [ "$(id -u)" = "0" ] || { echo "root 로 돌릴 것"; exit 2; }
}

# LAN 인터페이스를 고른다.
# ★★ `ip route get <자기 주소>` 를 쓰지 말 것 — 자기 주소는 **local** 경로라
#   `dev lo` 를 돌려준다. 첫 판이 그래서 MASQUERADE 를 `-o lo` 로 걸었고,
#   그러면 VPN 에서 다른 노드(104)로 가는 트래픽이 NAT 되지 않아 답이 돌아오지
#   못한다. **오류가 나지 않고 조용히 반쪽만 동작한다.**
#   기본 경로의 dev 를 쓰고, 그래도 lo 면 실패로 끝낸다.
lan_iface() {
  local i
  i=$(ip -o -4 route show default 2>/dev/null | awk '{for(k=1;k<=NF;k++) if($k=="dev") print $(k+1)}' | head -1)
  if [ -z "$i" ] || [ "$i" = "lo" ]; then
    # 두 번째 수단: 노드 주소를 들고 있는 인터페이스
    i=$(ip -o -4 addr show 2>/dev/null | awk -v ip="$NODE_IP/" '$4 ~ ip {print $2}' | head -1)
  fi
  case "$i" in
    ''|lo) printf '' ;;
    *) printf '%s' "$i" ;;
  esac
}

# ---------------------------------------------------------------- 와일드카드 DNS
# ★ 노드의 :53 은 systemd-resolved 가 **127.0.0.53/127.0.0.54 에만** 묶여
#   있어 LAN IP 의 53 이 비어 있다(실측). dnsmasq 를 그 주소에만 바인드하면
#   노드 자신의 DNS 를 건드리지 않는다 — Gotcha 111 의 되풀이를 피한다.
#   그 Gotcha 에서 DNS 를 고치는 층을 세 번 틀렸는데, 여기서는 아예 다른
#   주소에 서므로 그 사슬에 끼지 않는다.
dns_apply() {
  head2 "와일드카드 DNS"
  # ★★★ 패키지 `dnsmasq` 를 설치하지 않는다 — **전용 유닛**을 쓴다.
  #   실측으로 이 노드에는 `dnsmasq-base` 만 깔려 있었다(libvirt/NetworkManager
  #   가 끌고 온다): 바이너리 `/usr/sbin/dnsmasq` 는 있는데
  #   `dnsmasq.service` 도 `/etc/dnsmasq.conf` 도 **없다.** 첫 판이 바이너리
  #   유무로 판정해 설치를 건너뛰고 "기동 실패" 를 냈다 — **무엇이 있는지는
  #   쓰려는 그 물건으로 물을 것**(유닛을 쓸 거면 유닛을 보라).
  #   ★ 패키지를 깔면 전역 `/etc/dnsmasq.conf` 와 systemd-resolved 가 :53 을
  #     다투고, 이 레포는 그 사슬에서 한 번 크게 물렸다(Gotcha 111). 전용
  #     유닛 + 전용 설정이면 그 다툼이 아예 생기지 않는다.
  #   ★ `oim-thermal-policy.service`(Gotcha 192)와 같은 양식이다.
  local rc_before=""
  [ -e /etc/resolv.conf ] && rc_before=$(readlink -f /etc/resolv.conf 2>/dev/null)":"$(md5sum /etc/resolv.conf 2>/dev/null | awk '{print $1}')
  if [ ! -x "$DNSMASQ_BIN" ]; then
    echo "  dnsmasq-base 설치"
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq dnsmasq-base >/dev/null 2>&1 \
      || { bad "dnsmasq-base 설치 실패 (망을 확인할 것)"; return 1; }
  fi
  [ -x "$DNSMASQ_BIN" ] || { bad "$DNSMASQ_BIN 이 없다"; return 1; }
  if [ -n "$rc_before" ]; then
    local rc_after
    rc_after=$(readlink -f /etc/resolv.conf 2>/dev/null)":"$(md5sum /etc/resolv.conf 2>/dev/null | awk '{print $1}')
    if [ "$rc_before" != "$rc_after" ]; then
      bad "설치가 /etc/resolv.conf 를 바꿨다 ($rc_before -> $rc_after)"
      return 1
    fi
    ok "/etc/resolv.conf 가 그대로다 (설치가 노드 DNS 를 건드리지 않았다)"
  fi

  cat > "$DNSMASQ_CONF" <<EOF
# Generated by local/external-access-node.sh - ASCII only, do not edit by hand.
# Wildcard DNS for the cluster ingress. Bind only to the LAN address so that
# systemd-resolved keeps 127.0.0.53 for the node itself.
bind-interfaces
listen-address=$NODE_IP
# Upstreams come from /etc/resolv.conf (the systemd-resolved stub on this node).
# Do not restate them here - two places drift (see Gotcha 117).
address=/$DOMAIN/$NODE_IP
domain-needed
bogus-priv
no-hosts
cache-size=1000
EOF
  assert_ascii "$DNSMASQ_CONF" || { rm -f "$DNSMASQ_CONF"; return 1; }
  ok "$DNSMASQ_CONF 작성"
  # ★ 설정을 쓴 뒤 **문법 검사를 먼저** 한다. 틀린 설정으로 유닛을 걸면
  #   실패 원인이 유닛 쪽으로 읽힌다.
  if ! "$DNSMASQ_BIN" --test --conf-file="$DNSMASQ_CONF" >/dev/null 2>&1; then
    bad "dnsmasq 설정 문법 오류"
    "$DNSMASQ_BIN" --test --conf-file="$DNSMASQ_CONF" 2>&1 | sed 's/^/      /'
    return 1
  fi
  ok "dnsmasq 설정 문법 OK"

  cat > "$DNS_UNIT" <<EOF
[Unit]
Description=OIM wildcard DNS for *.$DOMAIN (generated, do not edit by hand)
Documentation=file:///root/oneinchmarket-dev/local/EXTERNAL-ACCESS.md
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStartPre=$DNSMASQ_BIN --test --conf-file=$DNSMASQ_CONF
ExecStart=$DNSMASQ_BIN --keep-in-foreground --conf-file=$DNSMASQ_CONF
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
  assert_ascii "$DNS_UNIT" || { rm -f "$DNS_UNIT"; return 1; }
  ok "$DNS_UNIT 작성"
  systemctl daemon-reload
  systemctl enable "$DNS_UNIT_NAME" >/dev/null 2>&1
  restart_verify "$DNS_UNIT_NAME" || return 1
  dns_check
}

dns_check() {
  if [ ! -x "$DNSMASQ_BIN" ]; then skip "$DNSMASQ_BIN 이 없다 (dnsmasq-base 미설치)"; return; fi
  [ -f "$DNSMASQ_CONF" ] && ok "설정 파일 있음" || bad "$DNSMASQ_CONF 없음"
  [ -f "$DNS_UNIT" ] && ok "유닛 파일 있음" || bad "$DNS_UNIT 없음"
  [ "$(systemctl is-active "$DNS_UNIT_NAME" 2>/dev/null)" = "active" ] \
    && ok "$DNS_UNIT_NAME active" || bad "$DNS_UNIT_NAME 이 active 가 아니다"
  [ "$(systemctl is-enabled "$DNS_UNIT_NAME" 2>/dev/null)" = "enabled" ] \
    && ok "$DNS_UNIT_NAME enabled (재부팅 생존)" || bad "$DNS_UNIT_NAME 이 enabled 가 아니다"
  # ★ 설정이 있는지가 아니라 **실제로 답하는지**로 판정한다. 임의의 라벨을
  #   물어 와일드카드가 사는지 본다 - 특정 호스트만 물으면 hosts 항목으로도
  #   통과해 버린다.
  if command -v dig >/dev/null 2>&1; then
    local a
    a=$(dig +short +time=3 +tries=1 "zz-wildcard-probe.$DOMAIN" @"$NODE_IP" 2>/dev/null \
        | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -1)
    [ "$a" = "$NODE_IP" ] && ok "와일드카드 질의 응답 = $NODE_IP" \
      || bad "와일드카드 질의가 '${a:-없음}' 을 돌려줬다 (기대 $NODE_IP)"
    # ★ 가드를 "비어 있지 않다" 로 두지 말 것 — `dig +short` 는 실패를
    #   **stdout 에** 찍으므로(`;; communications error to ...`) 그 문구가
    #   답으로 통과한다. 실제로 첫 판이 그렇게 거짓 OK 를 냈다(Gotcha 117·148).
    a=$(dig +short +time=3 +tries=1 example.com @"$NODE_IP" 2>/dev/null \
        | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -1)
    [ -n "$a" ] && ok "외부 이름도 풀린다 (example.com -> $a)" \
      || bad "외부 이름이 풀리지 않는다 - 업스트림을 볼 것"
  else
    skip "dig 가 없어 응답을 확인하지 못했다 (dnsutils 를 넣을 것)"
  fi
}

# ------------------------------------------------------------------- WireGuard
# ★ VPN 서브넷을 172.30.0.0/24 로 둔다. 10.88.x 류를 쓰지 않는 이유가 있다 -
#   이 클러스터의 **Pod CIDR 이 10.0.0.0/8** 이라 10.x 를 쓰면 그 안에 들어가
#   충돌한다(실측으로 확인했다).
# ★★ 클라이언트에 미는 라우트는 LAN 뿐이다. Pod·Service CIDR 을 밀지 않는다 -
#   그쪽으로 직접 가면 신원이 없어 default-deny 에 막히고(ipBlock CIDR 로는
#   node 신원이 매칭되지 않는다, Gotcha 187·197), 게이트웨이·db-gateway 를
#   지나는 경로는 신원이 있어서 그 문제가 없다. 우회로를 만들지 않는 쪽이
#   보안도 단순함도 낫다.
wg_apply() {
  head2 "WireGuard VPN"
  if ! command -v wg >/dev/null 2>&1; then
    echo "  wireguard-tools 설치"
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq wireguard-tools >/dev/null 2>&1 \
      || { bad "wireguard-tools 설치 실패"; return 1; }
  fi
  modprobe wireguard 2>/dev/null
  if [ -d /sys/module/wireguard ] || modinfo wireguard >/dev/null 2>&1; then
    ok "wireguard 커널 모듈 사용 가능"
  else
    bad "wireguard 커널 모듈이 없다 - 이 커널에서는 userspace 구현이 필요하다"
    return 1
  fi

  mkdir -p "$WG_DIR" "$WG_PEERS"
  chmod 700 "$WG_DIR" "$WG_PEERS"

  if [ ! -f "$WG_CONF" ]; then
    # ★ 키를 출력하지 않는다. 길이와 생성 여부만 보고한다 - 민감한 출력은
    #   마스킹해서 보여 주려 하지 말고 아예 보지 말 것(Gotcha 186).
    umask 077
    wg genkey > "$WG_DIR/server.key"
    wg pubkey < "$WG_DIR/server.key" > "$WG_DIR/server.pub"
    local lan_if
    lan_if=$(lan_iface)
    {
      echo "# Generated by local/external-access-node.sh - ASCII only, do not edit by hand."
      echo "# Peers are appended by: external-access-node.sh --peer <name>"
      echo "[Interface]"
      echo "Address = $VPN_SERVER_IP/24"
      echo "ListenPort = $VPN_PORT"
      echo "PostUp = iptables -t nat -A POSTROUTING -s $VPN_CIDR -o $lan_if -j MASQUERADE"
      echo "PostDown = iptables -t nat -D POSTROUTING -s $VPN_CIDR -o $lan_if -j MASQUERADE"
      echo "PrivateKey = $(cat "$WG_DIR/server.key")"
    } > "$WG_CONF"
    chmod 600 "$WG_CONF"
    ok "서버 설정 생성 (개인키 $(wc -c < "$WG_DIR/server.key") 바이트, 값은 출력하지 않는다)"
    if [ -n "$lan_if" ]; then ok "MASQUERADE 대상 인터페이스 = $lan_if"; else bad "LAN 인터페이스를 찾지 못했다 (lo 는 쓸 수 없다)"; fi
  else
    ok "서버 설정이 이미 있다 - 덮지 않는다 (덮으면 기존 피어가 전부 무효가 된다)"
    # ★ 다만 MASQUERADE 인터페이스는 **수리한다.** 첫 판이 `-o lo` 를 적었고
    #   그 상태로는 VPN 에서 다른 노드로 가는 트래픽이 조용히 끊긴다.
    #   키는 건드리지 않고 그 두 줄만 고친다 — 멱등이다.
    local want cur
    want=$(lan_iface)
    cur=$(grep -oE 'POSTROUTING -s [0-9./]+ -o [^ ]+' "$WG_CONF" 2>/dev/null \
          | awk '{print $NF}' | head -1)
    if [ -n "$want" ] && [ "$cur" != "$want" ]; then
      sed -i "s| -o ${cur} -j MASQUERADE| -o ${want} -j MASQUERADE|g" "$WG_CONF"
      ok "MASQUERADE 인터페이스를 수리했다 ($cur -> $want)"
      systemctl restart "wg-quick@$WG_IF" >/dev/null 2>&1
    else
      ok "MASQUERADE 인터페이스 = ${cur:-미설정}"
    fi
  fi
  assert_ascii "$WG_CONF" || return 1

  systemctl enable "wg-quick@$WG_IF" >/dev/null 2>&1
  restart_verify "wg-quick@$WG_IF" || return 1
  wg_check
}

wg_check() {
  if ! command -v wg >/dev/null 2>&1; then skip "wg 도구가 설치되지 않았다"; return; fi
  [ -f "$WG_CONF" ] && ok "서버 설정 있음" || { bad "$WG_CONF 없음"; return; }
  [ "$(stat -c '%a' "$WG_CONF" 2>/dev/null)" = "600" ] \
    && ok "설정 퍼미션 600" || bad "설정 퍼미션이 600 이 아니다"
  [ "$(systemctl is-active "wg-quick@$WG_IF" 2>/dev/null)" = "active" ] \
    && ok "wg-quick@$WG_IF active" || bad "wg-quick@$WG_IF 가 active 가 아니다"
  [ "$(systemctl is-enabled "wg-quick@$WG_IF" 2>/dev/null)" = "enabled" ] \
    && ok "wg-quick@$WG_IF enabled (재부팅 생존)" || bad "enabled 가 아니다"
  # 유닛 상태가 아니라 커널에 물어본다
  if ip -o link show "$WG_IF" >/dev/null 2>&1; then
    ok "인터페이스 $WG_IF 존재 ($(ip -o -4 addr show "$WG_IF" 2>/dev/null | awk '{print $4}' | head -1))"
  else
    bad "인터페이스 $WG_IF 가 없다"
  fi
  if ss -lun 2>/dev/null | grep -q ":$VPN_PORT "; then
    ok "UDP $VPN_PORT 수신 중"
  else
    bad "UDP $VPN_PORT 를 듣지 않는다"
  fi
  local n
  n=$(wg show "$WG_IF" peers 2>/dev/null | grep -c . || true)
  [ -n "$n" ] || n=0
  printf '  [정보]  등록된 피어 %s개 (발급: --peer <이름>)\n' "$n"
  # ★ ip_forward 값을 여기서 **선언하지 않는다** - 다른 곳과 두 벌이 되면
  #   어긋난다(Gotcha 117). 보고만 한다.
  [ "$(cat /proc/sys/net/ipv4/ip_forward 2>/dev/null)" = "1" ] \
    && ok "ip_forward=1" || bad "ip_forward=0 - VPN 에서 LAN 으로 가지 못한다"
}

# 피어 발급. ★ 설정을 **파일로만** 쓴다. 클라이언트 개인키를 화면에 찍으면
#   터미널 기록·세션 로그에 남고 그것은 되돌릴 수 없다(Gotcha 186).
wg_peer() {
  local name="$1"
  case "$name" in
    ''|*[!a-z0-9-]*) echo "피어 이름은 소문자·숫자·하이픈만: '$name'"; exit 2 ;;
  esac
  need_root
  [ -f "$WG_CONF" ] || { echo "서버 설정이 없다 - 먼저 인자 없이 한 번 돌릴 것"; exit 2; }
  command -v wg >/dev/null 2>&1 || { echo "wg 도구가 없다"; exit 2; }

  local out="$WG_PEERS/$name.conf"
  if [ -f "$out" ]; then
    echo "이미 있다: $out"
    echo "다시 만들려면 그 파일과 $WG_CONF 의 해당 [Peer] 절을 함께 지울 것."
    exit 0
  fi
  # 다음 주소를 고른다. ★ 목록을 파싱해 번호로 고르지 않는다 - 파이프로 존재를
  #   판정하면 pipefail·SIGPIPE 함정에 걸린다(Gotcha 109). 값을 변수에 받아
  #   case 로 가른다.
  local used next i
  used=" $(grep -oE 'AllowedIPs = 172\.30\.0\.[0-9]+' "$WG_CONF" 2>/dev/null \
            | grep -oE '[0-9]+$' | tr '\n' ' ') "
  next=""
  for i in $(seq 2 254); do
    case "$used" in *" $i "*) : ;; *) next="$i"; break ;; esac
  done
  [ -n "$next" ] || { echo "주소가 남지 않았다"; exit 1; }

  umask 077
  local key pub
  key=$(wg genkey)
  pub=$(printf '%s' "$key" | wg pubkey)
  {
    echo ""
    echo "[Peer]"
    echo "# $name"
    echo "PublicKey = $pub"
    echo "AllowedIPs = 172.30.0.$next/32"
  } >> "$WG_CONF"

  {
    echo "# WireGuard peer: $name  (generated, ASCII only)"
    echo "# Import this file into the WireGuard client. Keep it secret."
    echo "[Interface]"
    echo "Address = 172.30.0.$next/32"
    echo "DNS = $NODE_IP"
    echo "PrivateKey = $key"
    echo ""
    echo "[Peer]"
    echo "# Only the LAN is routed. Pod/Service CIDRs are deliberately NOT pushed -"
    echo "# see local/EXTERNAL-ACCESS.md section 5 for the reason."
    echo "PublicKey = $(cat "$WG_DIR/server.pub")"
    echo "AllowedIPs = $LAN_CIDR"
    echo "Endpoint = REPLACE_WITH_PUBLIC_ADDRESS:$VPN_PORT"
    echo "PersistentKeepalive = 25"
  } > "$out"
  chmod 600 "$out"
  assert_ascii "$out" || exit 1

  # 설정을 다시 읽힌다. 전체 재시작은 기존 세션을 끊으므로 syncconf 를 먼저 쓴다.
  if wg syncconf "$WG_IF" <(wg-quick strip "$WG_IF") 2>/dev/null; then
    echo "  실행 중 인터페이스에 반영했다 (기존 세션 유지)"
  else
    restart_verify "wg-quick@$WG_IF" || exit 1
  fi

  echo ""
  echo "피어 발급 완료: $name  ->  172.30.0.$next"
  echo "  파일: $out  (퍼미션 $(stat -c '%a' "$out"))"
  echo "  ★ 개인키가 들어 있어 화면에 찍지 않는다. 가져갈 것:"
  echo "      scp root@$NODE_IP:$out ."
  echo "  ★ Endpoint 의 REPLACE_WITH_PUBLIC_ADDRESS 를 바꿀 것:"
  echo "      집 안에서만 쓸 때 -> $NODE_IP"
  echo "      밖에서 쓸 때      -> 공유기의 공인 주소(또는 DDNS 이름)."
  echo "                           그리고 공유기에서 UDP $VPN_PORT 만 포워딩."
  echo "  등록된 피어: $(wg show "$WG_IF" peers 2>/dev/null | grep -c . || true)개"
}

limits() {
  cat <<'EOF'

-- 이 스크립트가 재지 못하는 것 ----------------------------------------------
  * 공유기 설정 - DHCP 가 배포하는 DNS 서버, UDP 51820 포트포워딩.
    둘 다 사람이 해야 하고 여기서는 보이지 않는다.
  * 클라이언트 기기의 DNS 설정(또는 hosts 파일).
  * 실제 부팅 경로 - 유닛이 enabled 인 것은 "재부팅에 살아난다" 를 뜻하지만
    펌웨어·디스크·NIC 문제는 여기서 보이지 않는다.
  * 443·80 경로 - 그것은 클러스터 쪽이다(external-ips-service.yaml).
    curl -k https://<노드IP>/ 로 따로 확인할 것.
  * DNS 와 VPN 은 이 노드 하나에 있다. 이 노드가 꺼지면 이름 해석과 원격
    접속이 함께 멈춘다 - 알고 고른 단일점이다.
EOF
}

main() {
  local mode="${1:-apply}"
  case "$mode" in
    --peer)
      [ $# -ge 2 ] || { echo "사용법: $0 --peer <이름>"; exit 2; }
      wg_peer "$2"; exit 0 ;;
    --check)
      echo "외부 접속 노드 전제 - 검사만"
      head2 "와일드카드 DNS (dnsmasq)"; dns_check
      head2 "WireGuard VPN";            wg_check
      ;;
    apply|'')
      need_root
      dns_apply
      wg_apply
      ;;
    *) echo "사용법: $0 [--check | --peer <이름>]"; exit 2 ;;
  esac

  printf '\n== 요약 ==\n  통과 %d · 실패 %d · 측정 불가 %d\n' "$PASS" "$FAIL" "$UNMEAS"
  limits
  # ★ 판정은 셋이다. 측정 불가를 통과로 접지 않는다 — 거짓 안심이 거짓
  #   경보보다 나쁘다(Gotcha 191·194).
  if [ "$FAIL" -gt 0 ]; then exit 1; fi
  if [ "$UNMEAS" -gt 0 ]; then exit 2; fi
  exit 0
}

main "$@"
