apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-rbf-router
spec:
  serviceName: hadoop-rbf-router-headless
  replicas: 2
  selector:
    matchLabels:
      app: hadoop-rbf-router
  template:
    metadata:
      labels:
        app: hadoop-rbf-router
    spec:
      containers:
        - name: hadoop-rbf-router
          image: apache/hadoop:3.4.1
          command:
            - bash
            - -lc
            - |
              hdfs --daemon start dfsrouter
              exec tail -F "$HADOOP_LOG_DIR"/*router*.log
          ports:
            - containerPort: 50071
              protocol: TCP
            - containerPort: 8111
              protocol: TCP
            - containerPort: 8888
              protocol: TCP
          env:
            - name: HADOOP_CONF_DIR
              value: /opt/hadoop/etc/hadoop
            - name: HADOOP_LOG_DIR
              value: /hadoop/logs
          volumeMounts:
            - name: hadoop-rbf-router-config
              mountPath: /opt/hadoop/etc/hadoop
            - name: pvc
              mountPath: /hadoop/logs
      volumes:
        - name: hadoop-rbf-router-config
          configMap:
            name: hadoop-rbf-router-configmap
        - name: pvc
          persistentVolumeClaim:
            claimName: hadoop-rbf-router-pvc