# OneinchMarket v2 - Dev Overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patches/replicas-dev.yaml
  - path: patches/resources-dev.yaml
  - path: patches/storage-dev.yaml

commonLabels:
  environment: dev

commonAnnotations:
  app.kubernetes.io/instance: oneinchmarket-dev
