apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cmmn-api
spec:
  serviceName: cmmn-api-headless
  replicas: 1
  selector:
    matchLabels:
      app: cmmn-api
  template:
    metadata:
      labels:
        app: cmmn-api
    spec:
      setHostnameAsFQDN: true
      containers:
        - name: cmmn-api
          image: inquotient/cmmn-api:latest
          ports:
            - containerPort: 8080
              protocol: TCP 
          env:
            - name: DB_HOST
              value: "jdbc:mariadb://cmmn-mariadb-0.cmmn-mariadb-headless.dev.svc.cluster.local/cmmn"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cmmn-api-secret
                  key: CMMN_DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cmmn-api-secret
                  key: CMMN_DB_PASSWORD
      securityContext:
        runAsUser: 0
        runAsGroup: 0