apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - defectdojo-configmap.yaml
  - defectdojo-service.yaml
  - defectdojo-initializer.yaml
  - defectdojo-django-deployment.yaml
  - defectdojo-celery-deployment.yaml
  - defectdojo-nginx-deployment.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "7"
