apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kyverno-disallow-root.yaml
  - kyverno-require-resources.yaml
  - kyverno-disallow-latest.yaml
  - kyverno-disallow-privilege-escalation.yaml
  - kyverno-require-labels.yaml
  - kyverno-require-probes.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
