apiVersion: v1
kind: Service
metadata:
  name: admin-headless
  labels:
    app.kubernetes.io/name: admin
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: oneinchmarket
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: admin
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
