apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-config
  labels:
    app.kubernetes.io/name: admin
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: oneinchmarket
    app.kubernetes.io/managed-by: kustomize
data:
  NEXTAUTH_URL: "http://admin-headless:3000"
  NODE_ENV: "development"
