apiVersion: v1 
kind: Service
metadata: 
  name: hive-metastore-nodeport
spec: 
  ports: 
    - name: hive-metastore-port
      port: 20000
      targetPort: 10000 
  selector: 
    app: hive-metastore 
  type: NodePort