apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny.yaml
  - database-netpol.yaml
  - messaging-netpol.yaml
  - observability-netpol.yaml
  - application-netpol.yaml
  - data-lakehouse-netpol.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
