apiVersion: v1 
kind: Service
metadata: 
  name: akhq-nodeport
spec: 
  ports: 
    - name: akhq-http-port 
      port: 58080
      targetPort: 8080 
  selector: 
    app: akhq 
  type: NodePort