apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ranger-admin
spec:
# whenDeleted를 Delete로 설정하면 pod가 지워지면 pvc도 같이 지워지도록 할 수 있다. 
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  serviceName: ranger-admin-headless
  replicas: 1
  selector:
    matchLabels:
      app: ranger-admin
  template:
    metadata:
      labels:
        app: ranger-admin
    spec:
      setHostnameAsFQDN: true
      containers:
        - name: ranger-admin
          image: apache/ranger:2.7.0
          command:
            - bash
            - -lc
            - |
              apt-get update && apt-get install -y lsb-release
              curl -fsSL https://downloads.apache.org/ranger/2.7.0/services/usersync/ranger-2.7.0-usersync.tar.gz | tar -xz -C /opt/ranger
              rm /opt/ranger/ranger-2.7.0-admin/install.properties
              update-ca-certificates
              cat /opt/ranger/ranger-2.7.0-admin/install.properties.temp > /opt/ranger/ranger-2.7.0-admin/install.properties
              echo " " >> /opt/ranger/ranger-2.7.0-admin/install.properties
              echo "db_root_password=$DB_ROOT_PASSWORD" >> /opt/ranger/ranger-2.7.0-admin/install.properties
              echo "db_password=$DB_PASSWORD" >> /opt/ranger/ranger-2.7.0-admin/install.properties
              echo "rangerAdmin_password=$RANGERADMIN_PASSWORD" >> /opt/ranger/ranger-2.7.0-admin/install.properties
              echo "rangerTagsync_password=$RANGERTAGSYNC_PASSWORD" >> /opt/ranger/ranger-2.7.0-admin/install.properties
              echo "rangerUsersync_password=$RANGERUSERSYNC_PASSWORD" >> /opt/ranger/ranger-2.7.0-admin/install.properties
              echo "keyadmin_password=$KEYADMIN_PASSWORD" >> /opt/ranger/ranger-2.7.0-admin/install.properties
              echo "audit_elasticsearch_password=$AUDIT_ELASTICSEARCH_PASSWORD" >> /opt/ranger/ranger-2.7.0-admin/install.properties
              echo "POLICY_MGR_URL=http://ranger-admin-headless.dev.svc.cluster.local:6080" >> /opt/ranger/ranger-2.7.0-admin/install.properties
              cat /opt/ranger/ranger-2.7.0-admin/install.properties
              /home/ranger/scripts/ranger.sh
          ports:
            - containerPort: 6080
              protocol: TCP
          env:
            - name: DB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgresql-configmap
                  key: postgresql_password
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ranger-admin-configmap
                  key: DB_PASSWORD
            - name: AUDIT_ELASTICSEARCH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ranger-admin-configmap
                  key: AUDIT_ELASTICSEARCH_PASSWORD
            - name: RANGERADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ranger-admin-configmap
                  key: RANGERADMIN_PASSWORD
            - name: RANGERTAGSYNC_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ranger-admin-configmap
                  key: RANGERTAGSYNC_PASSWORD
            - name: RANGERUSERSYNC_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ranger-admin-configmap
                  key: RANGERUSERSYNC_PASSWORD
            - name: KEYADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ranger-admin-configmap
                  key: KEYADMIN_PASSWORD
            - name: JAVA_OPTS
              value: >
                -Djavax.net.ssl.trustStore=/opt/ranger/truststore/ranger-truststore.jks
                -Djavax.net.ssl.trustStorePassword=changeit
                -Djavax.net.ssl.trustStoreType=JKS
            - name: RANGER_USERSYNC_HOME
              value: /opt/ranger/ranger-2.7.0-admin/ews/webapp/WEB-INF/classes/
            - name: RANGER_LOG_DIR
              value: /var/log/ranger
          volumeMounts:
            - name: ranger-admin-config
              mountPath: /opt/ranger/ranger-2.7.0-admin/install.properties.temp
              subPath: install.properties.temp
            - name: ranger-admin-config
              mountPath: /home/ranger/scripts/create-ranger-services.py
              subPath: create-ranger-services.py
            - name: ranger-admin-config
              mountPath: /opt/ranger/ranger-2.7.0-admin/conf/ranger-admin-site.xml
              subPath: ranger-admin-site.xml
            - name: hadoop-config
              mountPath: /opt/ranger/ranger-2.7.0-admin/conf/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: hadoop-config
              mountPath: /opt/ranger/ranger-2.7.0-admin/conf/core-site.xml
              subPath: core-site.xml
      volumes:
        - name: ranger-admin-config
          configMap:
            name: ranger-admin-configmap
            items:
              - key: install.properties
                path: install.properties.temp
              - key: create-ranger-services.py
                path: create-ranger-services.py
        - name: hadoop-config
          configMap:
            name: hadoop-configmap
            items:
              - key: hdfs-site.xml
                path: hdfs-site.xml
              - key: core-site.xml
                path: core-site.xml
#        - name: ranger-truststore
#          secret:
#            secretName: ranger-truststore
#        - name: es-http-ca
#          secret:
#            secretName: es-custom-cert
      securityContext:
        runAsUser: 0
        runAsGroup: 0
  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 20Gi