apiVersion: v1
kind: Service
metadata:
  name: hadoop-rbf-router-headless
spec:
  selector:
    app: hadoop-rbf-router
  ports:
    - port: 8888
      name: hadoop-rbf-router-rpc
    - port: 8111
      name: hadoop-rbf-router-admin
    - port: 50071
      name: hadoop-rbf-router-http
  clusterIP: None
  # 필요 시 LoadBalancer/Ingress로 외부 노출