apiVersion: v1 
kind: Service
metadata: 
  name: hadoop-rbf-router-nodeport
spec:
  selector:
    app: hadoop-rbf-router
  ports:
    - name: hadoop-rbf-router-http
      port: 60071
      targetPort: 50071
  type: NodePort