apiVersion: v1
kind: Service
metadata:
  name: asws-headless
  labels:
    app: apicurio-studio-ws
spec:
  ports:
  - port: 8080
    name: apicurio-studio-ws-port
  - port: 8443
    name: apicurio-studio-ws-secure-port
  clusterIP: None
  selector:
    app: apicurio-studio-ws