apiVersion: v1
kind: Service
metadata:
  name: hive-server-headless
  labels:
    app.kubernetes.io/name: hive-server
    app.kubernetes.io/component: data-lakehouse
    app.kubernetes.io/part-of: oneinchmarket
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 10000
      targetPort: thrift
      protocol: TCP
      name: thrift
    # ★ HTTP transport 포트 — Knox 가 이쪽으로 붙는다.
    - port: 10001
      targetPort: 10001
      protocol: TCP
      name: http-thrift
    - port: 10002
      targetPort: web
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: hive-server
