apiVersion: v1
kind: ServiceAccount
metadata:
  name: ranger-usersync
  labels: {app.kubernetes.io/name: ranger-usersync, app.kubernetes.io/component: governance, app.kubernetes.io/part-of: oneinchmarket, app.kubernetes.io/managed-by: kustomize}
automountServiceAccountToken: false
