apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-namenode
spec:
# whenDeleted를 Delete로 설정하면 pod가 지워지면 pvc도 같이 지워지도록 할 수 있다. 
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  serviceName: hadoop-namenode-headless
  replicas: 2
  selector:
    matchLabels:
      app: hadoop-namenode
  template:
    metadata:
      labels:
        app: hadoop-namenode
    spec:
      initContainers:
        - name: hadoop-namenode-init
          image: apache/hadoop:3.4.1
          command:
            - bash
            - -lc
            - |
              cat /opt/hadoop/etc/hadoop/hdfs-site.xml
              if [ ! -d /hadoop/dfs/name/current ]; then
                if [[ "$(hostname)" == *"-0" ]]; then
                  echo "==> namenode-0: format + init shared edits + zkfc format"
                  hdfs namenode -format -nonInteractive -force
                  hdfs namenode -initializeSharedEdits -force
                  hdfs zkfc -formatZK -force || true
                else
                  echo "==> namenode-1: bootstrap standby"
                  hdfs namenode -bootstrapStandby -nonInteractive
                fi
              fi
          env:
            - name: HADOOP_CONF_DIR
              value: /opt/hadoop/etc/hadoop
          volumeMounts:
            - name: pvc
              mountPath: /hadoop/dfs/name
            - name: pvc
              mountPath: /hadoop/logs
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop
      containers:
        - name: hadoop-namenode
          image: apache/hadoop:3.4.1
          command:
            - bash
            - -lc
            - |
              export HADOOP_LOG_DIR=/hadoop/logs
              if [ "${HOSTNAME}" = "hadoop-namenode-0" ]; then
                /usr/local/hadoop/bin/hdfs --config /etc/hadoop namenode -D hadoop.hdfs.namenode.id=nn1
              elif [ "${HOSTNAME}" = "hadoop-namenode-1" ]; then
                /usr/local/hadoop/bin/hdfs --config /etc/hadoop namenode -D hadoop.hdfs.namenode.id=nn2
              fi
              hdfs namenode
          ports:
            - containerPort: 8020
              protocol: TCP
            - containerPort: 9870
              protocol: TCP
          env:
            - name: HADOOP_CONF_DIR
              value: /opt/hadoop/etc/hadoop
            - name: HADOOP_LOG_DIR
              value: /hadoop/logs
          volumeMounts:
            - name: pvc
              mountPath: /hadoop/dfs/name
            - name: pvc
              mountPath: /hadoop/logs
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop
          readinessProbe:
            httpGet:
              path: /
              port: 9870
            initialDelaySeconds: 20
            periodSeconds: 10
        - name: zkfc
          image: apache/hadoop:3.4.1
          command: ["bash","-lc","hdfs zkfc"]
          env:
            - name: HADOOP_CONF_DIR
              value: /opt/hadoop/etc/hadoop
          volumeMounts:
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-configmap
  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "standard"
        resources:
          requests:
            storage: 50Gi