apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    app.kubernetes.io/name: prod
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: oneinchmarket
    app.kubernetes.io/managed-by: kustomize
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
