apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-journalnode
spec:
  serviceName: hadoop-journalnode-headless
  replicas: 5
  selector:
    matchLabels:
      app: hadoop-journalnode
  template:
    metadata:
      labels:
        app: hadoop-journalnode
    spec:
      containers:
        - name: hadoop-journalnode
          image: apache/hadoop:3.4.1
          command: ["bash","-lc","hdfs journalnode"]
          ports:
            - containerPort: 8485
              protocol: TCP
          env:
            - name: HADOOP_CONF_DIR
              value: /opt/hadoop/etc/hadoop
            - name: HADOOP_LOG_DIR
              value: /hadoop/logs
          volumeMounts:
            - name: pvc
              mountPath: /hadoop/dfs/journal
            - name: pvc
              mountPath: /hadoop/logs
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-configmap
  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 25Gi