apiVersion: v1
kind: Service
metadata:
  name: hive-server-headless
  labels:
    app: hive-server
spec:
  ports:
  - port: 10000
    name: hive-server-port
  - port: 10001
    name: hive-http-port
  clusterIP: None
  selector:
    app: hive-server