apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-es-cert
  namespace: dev
spec:
  isCA: true
  dnsNames:
    - elasticsearch-es-http
    - elasticsearch-es-http.dev.svc
    - elasticsearch-es-http.dev.svc.cluster.local
    - elasticsearch-es-all
    - elasticsearch-es-all.dev.svc
    - elasticsearch-es-all.dev.svc.cluster.local
    - elasticsearch-es-internal-http
    - elasticsearch-es-internal-http.dev.svc
    - elasticsearch-es-internal-http.dev.svc.cluster.local
    - elasticsearch-es-transport
    - elasticsearch-es-transport.dev.svc
    - elasticsearch-es-transport.dev.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: elasticsearch-es-cert
  subject:
    organizations:
      - oneinchmarket