apiVersion: v1
kind: Service
metadata:
  name: akhq-headless
  labels:
    app.kubernetes.io/name: akhq
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: oneinchmarket
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: akhq
