apiVersion: v1
kind: ConfigMap
metadata:
  name: akhq-config
  labels:
    app.kubernetes.io/name: akhq
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: oneinchmarket
data:
  application.yml: |
    akhq:
      connections:
        oneinchmarket:
          properties:
            bootstrap.servers: "kafka-0.kafka-headless:9092,kafka-1.kafka-headless:9092,kafka-2.kafka-headless:9092"
          schema-registry:
            url: "http://apicurio-registry-headless:8080/apis/ccompat/v7"
