apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  # whenDeleted를 Delete로 설정하면 pod가 지워지면 pvc도 같이 지워지도록 할 수 있다. 
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  serviceName: keycloak-headless
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      setHostnameAsFQDN: true
      initContainers:
        - name: download-providers
          image: fedora:latest
          args:
            - bash
            - -lc
            - |
              cd /providers
              curl -L -O https://repo1.maven.org/maven2/com/markstickel/keycloak/keycloak-kafka-publisher-event-listener-provider/1.0.0/keycloak-kafka-publisher-event-listener-provider-1.0.0.jar
              curl -L -O https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/4.1.1/kafka-clients-4.1.1.jar
          volumeMounts:
            - name: providers
              mountPath: /providers
      containers:
        - name: keycloak
          image: keycloak/keycloak:latest
          command:
            - bash
            - -lc
            - |
              /opt/keycloak/bin/kc.sh show-config
              /opt/keycloak/bin/kc.sh start --https-certificate-file=/opt/keycloak/tls/tls.crt --https-certificate-key-file=/opt/keycloak/tls/tls.key --verbose --
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          env:
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: keycloak-configmap
                  key: admin_password
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgresql-0.postgresql-headless.dev.svc.cluster.local:5432/keycloak"
            - name: KEYCLOAK_DATABASE_USER
              value: "keycloak"
            - name: KC_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: keycloak-configmap
                  key: keycloakdb_password
            - name: KC_DB_SCHEMA
              value: "keycloak"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: keycloak-configmap
                  key: admin_password
            - name: KC_CACHE
              value: "ispn"
            - name: KC_CACHE_CONFIG_FILE
              value: "cache-ispn.xml"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/"
            - name: KAFKA_TOPIC
              value: "keycloak-events"
            - name: KAFKA_BOOTSTRAP_SERVER
              value: "kafka-br-headless.dev.svc.cluster.local:9092"
            - name: KC_ADMIN_EVENTS_ENABLE
              value: "true"
            - name: KC_ADMIN_EVENTS_DETAILS_ENABLED
              value: "true"
            - name: KC_EVENT_LISTENERS
              value: "kafka"
#            - name: KC_SPI_EVENTS_LISTENER_HTTP_PUT_KEYCLOAK_KNOX_USER_URL
#              value: "argocd.oneinchmarket.co.kr"
#            - name: KC_SPI_EVENTS_LISTENER_HTTP_WEBHOOK_SECRET
#              value: "cfbf9996ddb2200a08de3fea3bfb841b6fbebd799a1518eee2ee084b0443aa73"
            - name: KC_SPI_EVENTS_LISTENER_KAFKA_TOPIC_EVENTS
              value: "keycloak-events"
            - name: KC_SPI_EVENTS_LISTENER_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-br-headless.dev.svc.cluster.local:9092"
            - name: KC_SPI_EVENTS_LISTENER_KAFKA_ACKS
              value: "1"
          volumeMounts:
            - name: pvc
              mountPath: /bitnami
              subPath: bitnami
            - name: tls
              mountPath: /opt/keycloak/tls
              readOnly: true
            - name: keycloak-store
              mountPath: /opt/keycloak/truststores
              readOnly: true
            - name: providers
              mountPath: /opt/keycloak/providers
      volumes:
        - name: keycloak-config
          configMap:
            name: keycloak-configmap
            items:
              - key: run.sh
                path: run.sh
                mode: 0755
        - name: tls
          secret:
            secretName: tls
        - name: keycloak-store
          secret:
            secretName: keycloak-store
        - name: providers
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 20Gi
