apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-configmap
data:
  admin_password: oxRvVn8df0CGWAN2T1tnPv0brM6/lTGq
  keycloak_store_password: 8a52be528235fa7c07f764b0376de12293a0dbd43d9477ce8fea203e988e38d4
  keycloakdb_password: tKUN/T9BNxMsVbD5q8jEzIFs2OxCFIHd