apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-configmap
data:
  admin_password: 5LLp+EDCebt7iN5j4iBIejo7JqSv4LTg
  keycloak_store_password: f79c725a44d50e69ae23d032de61311050c883571bf7ea609f8249218a446ed1
  keycloakdb_password: prafUNDiq7feHLsMt5qkG6hikdPNW6My
