apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/component: devops
    app.kubernetes.io/part-of: oneinchmarket
    app.kubernetes.io/managed-by: kustomize
data:
  GITLAB_OMNIBUS_CONFIG: |
    external_url 'http://gitlab-headless'
    nginx['listen_https'] = false
    nginx['listen_port'] = 80
    nginx['redirect_http_to_https'] = false

    postgresql['enable'] = false
    gitlab_rails['db_adapter'] = 'postgresql'
    gitlab_rails['db_host'] = 'postgresql-headless'
    gitlab_rails['db_port'] = 5432
    gitlab_rails['db_database'] = 'gitlab'
    gitlab_rails['db_username'] = 'gitlab'
    gitlab_rails['db_password'] = ENV['GITLAB_DB_PASSWORD']

    redis['enable'] = false
    gitlab_rails['redis_host'] = 'redis-headless'
    gitlab_rails['redis_port'] = 6379
    gitlab_rails['redis_password'] = ENV['REDIS_PASSWORD']

    puma['worker_processes'] = 0
    sidekiq['concurrency'] = 10

    prometheus_monitoring['enable'] = false
    gitlab_rails['monitoring_whitelist'] = ['0.0.0.0/0', '::1/128']
