apiVersion: v1 
kind: Service
metadata: 
  name: kafka-br-nodeport
spec: 
  ports: 
    - name: kafka-br-port 
      port: 19092
      targetPort: 9092
  selector: 
    app: kafka-br
  type: NodePort