apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knox-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx
  tls:
    - hosts: 
        - knox.oneinchmarket.co.kr
      secretName: tls
  rules:
    - host: "knox.oneinchmarket.co.kr"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: knox-nodeport
              port:
                number: 8443