apiVersion: v1
kind: Service
metadata:
  name: gravitee-management-api-headless
  labels:
    app.kubernetes.io/name: gravitee
    app.kubernetes.io/component: api-management
    app.kubernetes.io/part-of: oneinchmarket
    app.kubernetes.io/managed-by: kustomize
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: gravitee
    app.kubernetes.io/instance: management-api
  ports:
    - name: http
      port: 8083
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gravitee-gateway-headless
  labels:
    app.kubernetes.io/name: gravitee
    app.kubernetes.io/component: api-management
    app.kubernetes.io/part-of: oneinchmarket
    app.kubernetes.io/managed-by: kustomize
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: gravitee
    app.kubernetes.io/instance: gateway
  ports:
    - name: http
      port: 8082
      targetPort: http
      protocol: TCP
