apiVersion: v1
kind: ConfigMap
metadata:
  name: ds389-configmap
data:
  DS_DOMAIN: oneinchmarket.co.kr
  DS_SUFFIX_NAME: dc=oneinchmarket,dc=co,dc=kr
  DS_INSTANCE_NAME: ldap
  DS_DM_PASSWORD : DirectoryManagerPassword