apiVersion: v1 
kind: Service
metadata: 
  name: hbase-hmaster-nodeport
spec:
  selector:
    app: hbase-hmaster
  ports:
    - name: hbase-hmaster-http
      port: 26010
      targetPort: 16010
  type: NodePort