apiVersion: v1 
kind: Service
metadata: 
  name: apicurio-registry-ui-nodeport
spec: 
  ports: 
    - name: apicurio-registry-ui-http-port 
      port: 58081
      targetPort: 8080 
  selector: 
    app: apicurio-registry-ui 
  type: NodePort