apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper
  labels: {app.kubernetes.io/name: zookeeper, app.kubernetes.io/component: data-lakehouse, app.kubernetes.io/part-of: oneinchmarket, app.kubernetes.io/managed-by: kustomize}
automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  labels: {app.kubernetes.io/name: zookeeper, app.kubernetes.io/component: data-lakehouse, app.kubernetes.io/part-of: oneinchmarket, app.kubernetes.io/managed-by: kustomize}
spec:
  clusterIP: None
  ports:
    - {name: client, port: 2181, targetPort: 2181, protocol: TCP}
    - {name: peer, port: 2888, targetPort: 2888, protocol: TCP}
    - {name: leader, port: 3888, targetPort: 3888, protocol: TCP}
  selector: {app.kubernetes.io/name: zookeeper}
