apiVersion: v1
kind: ServiceAccount
metadata:
  name: apicurio-ui
  labels: {app.kubernetes.io/name: apicurio-ui, app.kubernetes.io/component: messaging, app.kubernetes.io/part-of: oneinchmarket, app.kubernetes.io/managed-by: kustomize}
automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: apicurio-ui
  labels: {app.kubernetes.io/name: apicurio-ui, app.kubernetes.io/component: messaging, app.kubernetes.io/part-of: oneinchmarket, app.kubernetes.io/managed-by: kustomize}
spec:
  ports: [{name: http, port: 8080, targetPort: 8080, protocol: TCP}]
  selector: {app.kubernetes.io/name: apicurio-ui}
