apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco
  labels:
    app.kubernetes.io/name: falco
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: oneinchmarket
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco
  labels:
    app.kubernetes.io/name: falco
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: oneinchmarket
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods", "replicationcontrollers", "services", "events", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/healthz", "/healthz/*"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falco
  labels:
    app.kubernetes.io/name: falco
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: oneinchmarket
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: falco
subjects:
  - kind: ServiceAccount
    name: falco
    namespace: dev
