apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - admin/admin-statefulset.yaml
  - admin/admin-headless.yaml
  - admin/admin-configmap.yaml
  - cmmn-api/cmmn-api-statefulset.yaml
  - cmmn-api/cmmn-api-headless.yaml
  - cmmn-api/cmmn-api-secret.enc.yaml
  - nginx/nginx-deployment.yaml
  - nginx/nginx-service.yaml
  - nginx/nginx-configmap.yaml
