apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx
  tls:
    - hosts: 
        - argocd.oneinchmarket.co.kr
      secretName: tls
  rules:
    - host: "argocd.oneinchmarket.co.kr"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: argocd-server
              port:
                number: 443
#        - pathType: Prefix
#          path: "/webhook/keycloak-knox-user"
#          backend:
#            service:
#              name: argocd-server
#              port:
#                number: 12000