apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - safeline-service.yaml
  - safeline-deployment.yaml
  - safeline-aux-deployment.yaml

commonAnnotations:
  # 다른 서비스 앞단에 서므로 마지막에 올라온다.
  argocd.argoproj.io/sync-wave: "8"
