apiVersion: v1
kind: Service
metadata:
  name: asui-headless
  labels:
    app: apicurio-studio-ui
spec:
  ports:
  - port: 8080
    name: apicurio-studio-ui-port
  - port: 8443
    name: apicurio-studio-ui-secure-port
  clusterIP: None
  selector:
    app: apicurio-studio-ui