apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: keycloak-webhook
  namespace: argocd
spec:
  webhook:
    keycloak-knox--user-create:
      port: "12000"
      endpoint: /webhook/keycloak-knox-user
      method: PUT
      url: ""            # 외부 URL 설정은 Ingress에서 처리
      authSecret:
        name: webhook-secret
        key: webhook-secret