apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: keycloak-kafka-es
  namespace: argo-events
spec:
  kafka:
    keycloak-events:
      url: kafka-0.kafka-headless.dev.svc.cluster.local:9092
      topic: keycloak-events
      consumerGroup: keycloak-argo-consumer
      jsonBody: true 