apiVersion: v1
kind: Service
metadata:
  name: hbase-hmaster-headless
spec:
  ports:
    - port: 16000
      name: hbase-hmaster-rpc
    - port: 16010
      name: hbase-hmaster-http
  clusterIP: None
  selector:
    app: hbase-hmaster