apiVersion: v1
kind: Service
metadata:
  name: jenkins-nodeport
spec:
  ports:
    - name: jenkins-web-port
      port: 18080
      targetPort: 8080
    - name: jenkins-secure-port
      port: 18443
      targetPort: 8443
    - name: jenkins-jnlp-port
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins
  type: NodePort