apiVersion: v1 
kind: Service
metadata: 
  name: kafka-ctrl-nodeport
spec: 
  ports: 
    - name: kafka-ctrl-port 
      port: 29094
      targetPort: 9094 
  selector: 
    app: kafka-ctrl
  type: NodePort