apiVersion: v1
kind: Service
metadata:
  name: kafka-ctrl-headless
  labels:
    app: kafka-ctrl
spec:
  ports:
  - port: 9092
    name: kafka-ctrl-listner-port
  - port: 9093
    name: kafka-ctrl-port
  - port: 9094
    name: kafka-ctrl-internal-port
  clusterIP: None
  selector:
    app: kafka-ctrl