apiVersion: v1
kind: Service
metadata:
  name: ranger-admin-headless
  labels:
    app: ranger
spec:
  ports:
  - port: 6080
    name: ranger-admin-port
  clusterIP: None
  selector:
    app: ranger-admin