apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Keycloak
  - keycloak-statefulset.yaml
  - keycloak-headless.yaml
  - keycloak-configmap.yaml
  - keycloak-secret.enc.yaml

  # Kyverno Policies
  - kyverno-disallow-root.yaml
  - kyverno-require-resources.yaml
  - kyverno-disallow-latest.yaml
  - kyverno-disallow-privilege-escalation.yaml
  - kyverno-require-labels.yaml
  - kyverno-require-probes.yaml

  # Pod Security Standards - Namespaces
  - namespace-dev.yaml
  - namespace-prod.yaml
