apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-configmap
data:
  hive-metastore-db-password: "Hs5HSatTjTivgwPm9Kw8RylEZoVoRddE"
  hive-metastore-config: |-
    <?xml version="1.0"?>
    <configuration>

      <!-- Metastore 모드: remote -->
      <property>
        <name>hive.metastore.uris</name>
        <value></value>
      </property>

      <!-- Metastore 서비스가 열릴 포트 -->
      <property>
        <name>hive.metastore.port</name>
        <value>9083</value>
      </property>

      <property>
        <name>hive.metastore.thrift.bind.host</name>
        <value>0.0.0.0</value>
      </property>

      <!-- Warehouse 위치 (HDFS) -->
      <property>
        <name>fs.defaultFS</name>
        <value>hdfs://hdfs-ns-kr</value>
      </property>

      <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>/warehouse/tables</value>
      </property>

      <!-- DB 연결 설정 (MariaDB/MySQL) -->
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://postgresql-0.postgresql-headless.dev.svc.cluster.local:5432/hive_metastore</value>
      </property>

      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>

      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>${env.METASTORE_DB_USER}</value>
      </property>

      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>${env.METASTORE_DB_PASSWORD}</value>
      </property>

      <!-- JDO schema auto-create -->
      <property>
        <name>datanucleus.autoCreateSchema</name>
        <value>true</value>
      </property>

      <property>
        <name>datanucleus.autoCreateTables</name>
        <value>true</value>
      </property>

      <!-- Event notifications (HS2, Iceberg 등에서 필요할 수 있음) -->
      <property>
        <name>hive.metastore.event.db.notification.api.auth</name>
        <value>false</value>
      </property>

      <!-- 커넥션 풀 타입 선택 -->
      <property>
        <name>datanucleus.connectionPoolingType</name>
        <value>HikariCP</value>
      </property>

      <!-- Hikari 최대 풀 크기 -->
      <property>
        <name>datanucleus.connectionPool.maxPoolSize</name>
        <value>5</value>
      </property>

      <property>
        <name>datanucleus.connectionPool.minPoolSize</name>
        <value>1</value>
      </property>

      <!-- 커넥션 최대 lifetime (ms) -->
      <property>
        <name>datanucleus.connectionPool.maxLifetime</name>
        <value>1800000</value> <!-- 30분 -->
      </property>
    </configuration>
