apiVersion: v1
kind: Service
metadata:
  name: hive-metastore-headless
  labels:
    app: hive-metastore
spec:
  ports:
  - port: 9083
    name: hive-thrift-port
  - port: 10000
    name: hive-metastore-port
  - port: 10002
    name: hive-http-port
  clusterIP: None
  selector:
    app: hive-metastore