apiVersion: v1
kind: Service
metadata:
  name: mariadb-headless
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: oneinchmarket
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3306
      targetPort: mariadb
      protocol: TCP
      name: mariadb
  selector:
    app.kubernetes.io/name: mariadb
