apiVersion: v1
kind: Service
metadata:
  name: opensearch-headless
  labels: {app.kubernetes.io/name: opensearch, app.kubernetes.io/component: observability, app.kubernetes.io/part-of: oneinchmarket, app.kubernetes.io/managed-by: kustomize}
spec:
  clusterIP: None
  selector: {app.kubernetes.io/name: opensearch}
  ports:
    - {name: https, port: 9200, targetPort: 9200, protocol: TCP}
    - {name: transport, port: 9300, targetPort: 9300, protocol: TCP}
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboards
  labels: {app.kubernetes.io/name: opensearch-dashboards, app.kubernetes.io/component: observability, app.kubernetes.io/part-of: oneinchmarket, app.kubernetes.io/managed-by: kustomize}
spec:
  selector: {app.kubernetes.io/name: opensearch-dashboards}
  ports:
    - {name: http, port: 5601, targetPort: 5601, protocol: TCP}
