# Dev 환경: 스토리지 축소
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
spec:
  volumeClaimTemplates:
    - metadata:
        name: gitlab-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 20Gi
