apiVersion: v1
kind: Service
metadata:
  name: falcosidekick
  labels:
    app.kubernetes.io/name: falcosidekick
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: oneinchmarket
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: falcosidekick
  ports:
    - port: 2801
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
