apiVersion: v1 
kind: Service
metadata: 
  name: hbase-regionserver-nodeport
spec:
  selector:
    app: hbase-regionserver
  ports:
    - name: hbase-regionserver-http
      port: 26030
      targetPort: 16030
  type: NodePort