# SOPS 암호화 대상
apiVersion: v1
kind: Secret
metadata:
  name: apicurio-secret
  labels:
    app.kubernetes.io/name: apicurio-registry
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: oneinchmarket
type: Opaque
stringData:
  db-password: "PLACEHOLDER_ENCRYPT_WITH_SOPS"
