apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Kafka KRaft
  - kafka/kafka-statefulset.yaml
  - kafka/kafka-headless.yaml
  - kafka/kafka-configmap.yaml
  # Apicurio Registry
  - apicurio/apicurio-statefulset.yaml
  - apicurio/apicurio-headless.yaml
  # - apicurio/apicurio-secret.enc.yaml  # SOPS: re-enable after ArgoCD SOPS plugin setup
  # AKHQ
  - akhq/akhq-statefulset.yaml
  - akhq/akhq-headless.yaml
  - akhq/akhq-configmap.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
