apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Kafka KRaft
  - kafka-statefulset.yaml
  - kafka-headless.yaml
  - kafka-configmap.yaml
  # Apicurio Registry
  - apicurio-statefulset.yaml
  - apicurio-headless.yaml
  - apicurio-secret.enc.yaml
  # AKHQ
  - akhq-statefulset.yaml
  - akhq-headless.yaml
  - akhq-configmap.yaml
