apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-scanner
  labels:
    app.kubernetes.io/name: trivy-scanner
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: oneinchmarket
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-scanner
  labels:
    app.kubernetes.io/name: trivy-scanner
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: oneinchmarket
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trivy-scanner
  labels:
    app.kubernetes.io/name: trivy-scanner
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: oneinchmarket
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-scanner
subjects:
  - kind: ServiceAccount
    name: trivy-scanner
    namespace: dev
