apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-ctrl
spec:
  # whenDeleted를 Delete로 설정하면 pod가 지워지면 pvc도 같이 지워지도록 할 수 있다. 
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  serviceName: kafka-ctrl-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka-ctrl
  template:
    metadata:
      labels:
        app: kafka-ctrl
    spec:
      setHostnameAsFQDN: true
      containers:
        - name: kafka-ctrl
          image: apache/kafka:4.1.1
          command:
            - bash
            - -lc
            - |
              export KAFKA_NODE_ID=$(echo "$HOSTNAME" | awk -F'.' '{print $1}' | awk -F'-' '{print $3 + 1}')
              
              ls -l /opt/kafka/config 
              cat /opt/kafka/config/server.properties >> /opt/kafka/config/generated/server.properties

              echo "$HOSTNAME" | echo "node.id=$(awk -F'.' '{print $1}' | awk -F'-' '{print $3 + 1}')" >> /opt/kafka/config/generated/server.properties
              echo ${KAFKA_CONTROLLER_QUORUM_VOTERS} | echo "controller.quorum.bootstrap.servers=$(sed 's/[0-9]*@//g')" >> /opt/kafka/config/generated/server.properties

              cat /opt/kafka/config/generated/server.properties

              if [[ "$KAFKA_NODE_ID" == "1" ]]; then
                /opt/kafka/bin/kafka-storage.sh format --cluster-id ${KAFKA_CLUSTER_ID} --standalone --config /opt/kafka/config/generated/server.properties
                echo $KAFKA_NODE_ID
                /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/generated/server.properties
              else
                /opt/kafka/bin/kafka-storage.sh format --cluster-id ${KAFKA_CLUSTER_ID} --config /opt/kafka/config/generated/server.properties --no-initial-controllers
                /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/generated/server.properties
                /opt/kafka/bin/kafka-metadata-quorum.sh --command-config /opt/kafka/config/generated/server.properties --bootstrap-controller kafka-ctrl-0.kafka-ctrl-headless.dev.svc.cluster.local:9093 add-controller
              fi
          ports:
            - containerPort: 9092
              protocol: TCP
            - containerPort: 9093
              protocol: TCP
            - containerPort: 9094
              protocol: TCP
          env:
            - name: KAFKA_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: kafka_cluster_id
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-ctrl-0.kafka-ctrl-headless.dev.svc.cluster.local:9093,2@kafka-ctrl-1.kafka-ctrl-headless.dev.svc.cluster.local:9093,3@kafka-ctrl-2.kafka-ctrl-headless.dev.svc.cluster.local:9093"
          volumeMounts:
            - name: kafka-config
              mountPath: /opt/kafka/config/generated
            - name: kafka-server-config
              mountPath: /opt/kafka/config/server.properties
              subPath: server.properties
              readOnly: false
      volumes:
        - name: kafka-server-config
          configMap:
            name: kafka-ctrl-configmap
            items:
              - key: kafka-server-config
                path: server.properties
        - name: kafka-config
          emptyDir: {}
      #            - name: pvc

      #              mountPath: /bitnami/kafka/data

      #              subPath: data      
      securityContext:
        runAsUser: 0
        runAsGroup: 0
  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 20Gi
