apiVersion: v1
kind: Service
metadata:
  name: akhq-headless
  labels:
    app: akhq
spec:
  ports:
  - port: 8080
    name: akhq-port
  - port: 4000
    name: akhq-node-port
  clusterIP: None
  selector:
    app: akhq