apiVersion: v1
kind: ConfigMap
metadata:
  name: akhq-configmap
data:
  application-config: |
    micronaut:
      security:
        enabled: true
        oauth2:
          enabled: true
          clients:
            keycloak:
              client-id: "akhq"
              client-secret: "K9C0JUE0zqXNfmABaSIs7NCBikjrtSAl"
              openid:
                issuer: "http://keycloak-0.keycloak-headless.dev.svc.cluster.local:8080/realms/akhq"
        token:
          jwt:
            signatures:
              secret:
                generator:
                  secret: "K9C0JUE0zqXNfmABaSIs7NCBikjrtSAl"
    akhq:
      server:
        access-log:
          enabled: true
          name: org.akhq.log.access # Logger name
          format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}] [Length: {}]"
        #customHttpResponseHeaders:
        #  - name: "Content-Security-Policy"
        #    value: "default-src 'none'; frame-src 'self'; script-src 'self'; #connect-src 'self'; img-src 'self'; style-src 'self'; frame-ancestors 'self'; form-action 'self'; upgrade-insecure-requests"
        #  - name: "X-Permitted-Cross-Domain-Policies"
        #    value: "none"
      clients-defaults:
        consumer:
          properties:
            isolation.level: read_committed
      connections:
        akhq-cluster:
          properties:
            bootstrap.servers: "kafka-br-headless.dev.svc.cluster.local:9092"
          schema-registry:
            url: "http://ar-headless.dev.svc.cluster.local:8080/apis/ccompat/v7"
            type: "confluent"
          ui-options:
            topic:
              default-view: ALL
              skip-consumer-groups: false
              skip-last-record: true
              show-all-consumer-groups: true
              groups-default-view: ALL
            topic-data:
              sort: NEWEST
              date-time-format: ISO
      pagination:
        page-size: 25
        threads: 16
      avro-serializer:
        json.serialization.inclusions:
          - NON_NULL
      topic:
        retention: 172800000
        partition: 3
        replication: 3
        internal-regexps:
          - "^_.*$"
          - "^.*_schemas$"
          - "^.*connect-config$"
          - "^.*connect-offsets$1"
          - "^.*connect-status$"
        stream-regexps:
          - "^.*-changelog$"
          - "^.*-repartition$"
          - "^.*-rekey$"
        skip-consumer-groups: false
        skip-last-record: false
        show-all-consumer-groups: false
        retry:
          topic-exists:
            delay: "3s"
      topic-data:
        size: 50
        poll-timeout: 1000
        kafka-max-message-length: 1000000
      ui-options:
        topic:
          default-view: ALL
          skip-consumer-groups: false
          skip-last-record: true
          show-all-consumer-groups: true
          groups-default-view: ALL
        topic-data:
          sort: NEWEST
      security:
        roles:
          node-read:
            - resources: [ "NODE" ]
              actions: [ "READ", "READ_CONFIG" ]
          node-admin:
            - resources: [ "NODE" ]
              actions: [ "READ", "READ_CONFIG", "ALTER_CONFIG" ]
          topic-read:
            - resources: [ "TOPIC", "TOPIC_DATA" ]
              actions: [ "READ" ]
            - resources: [ "TOPIC" ]
              actions: [ "READ_CONFIG" ]
          topic-admin:
            - resources: [ "TOPIC", "TOPIC_DATA" ]
              actions: [ "READ", "CREATE", "DELETE" ]
            - resources: [ "TOPIC" ]
              actions: [ "UPDATE", "READ_CONFIG", "ALTER_CONFIG" ]
          connect-rw:
            - resources: [ "CONNECTOR" ]
              actions: [ "READ", "CREATE", "UPDATE_STATE" ]
          connect-admin:
            - resources: [ "CONNECTOR" ]
              actions: [ "READ", "CREATE", "UPDATE_STATE", "DELETE" ]
          registry-read:
            - resources: [ "SCHEMA" ]
              actions: [ "READ" ]
          registry-admin:
            - resources: [ "SCHEMA" ]
              actions: [ "READ", "CREATE", "UPDATE", "DELETE", "DELETE_VERSION" ]
          group-read:
            - resources: [ "CONSUMER_GROUP" ]
              actions: [ "READ" ]
          connect-cluster-read:
            - resources: [ "CONNECT_CLUSTER" ]
              actions: [ "READ" ]
          ksqldb-admin:
            - resources: [ "KSQLDB" ]
              actions: [ "READ", "EXECUTE" ]
        groups:
          admin:
            - role: node-admin
            - role: topic-admin
            - role: connect-admin
            - role: registry-admin
            - role: group-read
            - role: connect-cluster-read
            - role: ksqldb-admin
          topic-reader:
            - role: topic-read
            - role: registry-admin
          topic-reader-dev:
            - role: topic-read
              clusters: ["dev"]
            - role: registry-admin
              clusters: ["dev"]
          topic-reader-project-prod:
            - role: topic-read
              patterns: ["project.*"]
              clusters: ["prod.*"]
            - role: registry-admin
              patterns: ["project.*"]
              clusters: ["prod.*"]
        default-group: admin
        oidc:
          enabled: true
          providers:
            keycloak:
              label: "Login with OIDC"
              username-field: username
              groups-field: roles
              default-group: topic-reader
              groups:
                - name: oidc-admin-group
                  groups:
                    - admin
              users:
                - username: admin
                  groups:
                    - admin