apiVersion: v1
kind: Service
metadata:
  name: trino-headless
  labels:
    app.kubernetes.io/name: trino
    app.kubernetes.io/component: data-lakehouse
    app.kubernetes.io/part-of: oneinchmarket
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: trino
