apiVersion: v1
kind: Service
metadata:
  name: kafka-rest-headless
  labels:
    app: kafka-rest
spec:
  ports:
  - port: 8082
    name: kafka-rest-port
  clusterIP: None
  selector:
    app: kafka-rest