apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-rest-configmap
data:
  kafka-rest.properties: |
    ############################
    # Kafka REST Proxy 기본 설정
    ############################

    # REST Proxy 자체 설정
    listeners=http://0.0.0.0:8082
    host.name=cp-kafka-rest

    # Kafka Bootstrap Servers
    bootstrap.servers=kafka-br-headless.dev.svc.cluster.local:9092

    ############################
    # REST 기본 동작
    ############################
    client.id=kafka-rest-proxy
    consumer.request.timeout.ms=30000
    consumer.fetch.min.bytes=1
    consumer.fetch.wait.max.ms=500
    consumer.auto.offset.reset=earliest

    ############################
    # Schema Registry (선택)
    ############################
    #schema.registry.url=http://apicurio-registry-ui.dev.svc.cluster.local:8080